TESTING = False

if TESTING:
    # Game
    GAME_GRID_SIZE = 10

    # Ships
    NUM_CARRIER = 1
    NUM_BATTLESHIP = 0
    NUM_CRUISER = 0
    NUM_SUBMARINE = 1
    NUM_DESTROYER = 1

    LEN_CARRIER = 6
    LEN_BATTLESHIP = 4
    LEN_CRUISER = 3
    LEN_SUBMARINE = 3
    LEN_DESTROYER = 2

    ID_CARRIER = 1
    ID_BATTLESHIP = 2
    ID_CRUISER = 3
    ID_SUBMARINE = 4
    ID_DESTROYER = 5
    
else:
    # Game
    GAME_GRID_SIZE = 10

    # Ships
    NUM_CARRIER = 1
    NUM_BATTLESHIP = 2
    NUM_CRUISER = 2
    NUM_SUBMARINE = 1
    NUM_DESTROYER = 4
    
    LEN_CARRIER = 6
    LEN_BATTLESHIP = 4
    LEN_CRUISER = 3
    LEN_SUBMARINE = 3
    LEN_DESTROYER = 2
    
    ID_CARRIER = 1
    ID_BATTLESHIP = 2
    ID_CRUISER = 3
    ID_SUBMARINE = 4
    ID_DESTROYER = 5

HIT = 'X'
MISS = '-'
BOMBED = HIT